# -*- coding: utf-8 -*-
"""[#2941] 크로아티아 알파벳.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rGlN8uidfOG3JWS5_uCHyzWP9zCJ8G3O
"""

sen = str(input())
li =["c=", "c-", "d-","dz=", "lj", "nj", "s=","z="]
cnt =0
for i in range(len(li)):
  cnt += sen.count(li[i])  

print(len(sen)-cnt)